# STAGE MAVEN_BUILD
FROM maven:3-eclipse-temurin-17 AS maven_build

WORKDIR /s-pipes

COPY ./ ./

RUN mvn clean package -T 2C -DskipTests -q


# FINAL STAGE
FROM tomcat:9-jdk17-temurin

EXPOSE 8080

RUN rm -rf /usr/local/tomcat/webapps/*

COPY --from=maven_build "/s-pipes/s-pipes-debug/target/s-pipes-debug-*[0-9]" /usr/local/tomcat/webapps/s-pipes-debug

CMD ["catalina.sh","run"]