
package cz.cvut.spipes.model;

import cz.cvut.kbss.jopa.model.annotations.*;
import cz.cvut.kbss.jopa.vocabulary.DC;
import cz.cvut.kbss.jopa.vocabulary.RDFS;
import cz.cvut.spipes.Vocabulary;

import java.util.Map;
import java.util.Set;


/**
 * This class was generated by the OWL2Java tool version $VERSION$
 * 
 */
@OWLClass(iri = Vocabulary.s_c_dataset_publication)
public class DatasetPublication
    extends Thing
{

    @OWLAnnotationProperty(iri = RDFS.LABEL)
    protected String name;
    @OWLAnnotationProperty(iri = DC.Elements.DESCRIPTION)
    protected String description;
    @Types
    protected Set<String> types;
    @Id(generated = true)
    protected String id;
    @Properties
    protected Map<String, Set<Object>> properties;
    @OWLObjectProperty(iri = Vocabulary.s_p_has_published_dataset_snapshot)
    @ParticipationConstraints({
        @ParticipationConstraint(owlObjectIRI = Vocabulary.s_c_dataset_snapshot, max = 1)
    })
    protected DatasetSnapshot has_published_dataset_snapshot;
    @OWLObjectProperty(iri = Vocabulary.s_p_has_publisher)
    @ParticipationConstraints({
        @ParticipationConstraint(owlObjectIRI = Vocabulary.s_c_publisher, max = 1)
    })
    protected Set<Thing> has_publisher;

    public void setName(String name) {
        this.name = name;
    }

    public String getName() {
        return name;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public String getDescription() {
        return description;
    }

    public void setTypes(Set<String> types) {
        this.types = types;
    }

    public Set<String> getTypes() {
        return types;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getId() {
        return id;
    }

    public void setProperties(Map<String, Set<Object>> properties) {
        this.properties = properties;
    }

    public Map<String, Set<Object>> getProperties() {
        return properties;
    }

    public void setHas_published_dataset_snapshot(DatasetSnapshot has_published_dataset_snapshot) {
        this.has_published_dataset_snapshot = has_published_dataset_snapshot;
    }

    public DatasetSnapshot getHas_published_dataset_snapshot() {
        return has_published_dataset_snapshot;
    }

    public void setHas_publisher(Set<Thing> has_publisher) {
        this.has_publisher = has_publisher;
    }

    public Set<Thing> getHas_publisher() {
        return has_publisher;
    }

}
