
package cz.cvut.spipes.model;

import cz.cvut.kbss.jopa.model.annotations.*;
import cz.cvut.kbss.jopa.vocabulary.DC;
import cz.cvut.kbss.jopa.vocabulary.RDFS;
import cz.cvut.spipes.Vocabulary;

import java.util.Map;
import java.util.Set;


/**
 * This class was generated by the OWL2Java tool version $VERSION$
 * 
 */
@OWLClass(iri = Vocabulary.s_c_data)
public class Data
    extends Thing
{

    @OWLAnnotationProperty(iri = RDFS.LABEL)
    protected String name;
    @OWLAnnotationProperty(iri = DC.Elements.DESCRIPTION)
    protected String description;
    @Types
    protected Set<String> types;
    @Id(generated = true)
    protected String id;
    @Properties
    protected Map<String, Set<Object>> properties;
    @OWLObjectProperty(iri = Vocabulary.s_p_has_member)
    @ParticipationConstraints({
        @ParticipationConstraint(owlObjectIRI = Vocabulary.s_c_data_item, max = -1)
    })
    protected Set<Thing> has_member;
    @OWLObjectProperty(iri = Vocabulary.s_p_inv_dot_constitutes)
    @ParticipationConstraints({
        @ParticipationConstraint(owlObjectIRI = Vocabulary.s_c_dataset_snapshot, max = 1)
    })
    protected DatasetSnapshot inv_dot_constitutes;
    @OWLObjectProperty(iri = Vocabulary.s_p_is_part_of)
    @ParticipationConstraints({
        @ParticipationConstraint(owlObjectIRI = Vocabulary.s_c_data, max = 1)
    })
    protected Set<Thing> is_part_of;

    public void setName(String name) {
        this.name = name;
    }

    public String getName() {
        return name;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public String getDescription() {
        return description;
    }

    public void setTypes(Set<String> types) {
        this.types = types;
    }

    public Set<String> getTypes() {
        return types;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getId() {
        return id;
    }

    public void setProperties(Map<String, Set<Object>> properties) {
        this.properties = properties;
    }

    public Map<String, Set<Object>> getProperties() {
        return properties;
    }

    public void setHas_member(Set<Thing> has_member) {
        this.has_member = has_member;
    }

    public Set<Thing> getHas_member() {
        return has_member;
    }

    public void setInv_dot_constitutes(DatasetSnapshot inv_dot_constitutes) {
        this.inv_dot_constitutes = inv_dot_constitutes;
    }

    public DatasetSnapshot getInv_dot_constitutes() {
        return inv_dot_constitutes;
    }

    public void setIs_part_of(Set<Thing> is_part_of) {
        this.is_part_of = is_part_of;
    }

    public Set<Thing> getIs_part_of() {
        return is_part_of;
    }

}
