
package cz.cvut.spipes.model;

import cz.cvut.kbss.jopa.model.annotations.*;
import cz.cvut.kbss.jopa.vocabulary.DC;
import cz.cvut.kbss.jopa.vocabulary.RDFS;
import cz.cvut.spipes.Vocabulary;

import java.util.Map;
import java.util.Set;


/**
 * This class was generated by the OWL2Java tool version $VERSION$
 * 
 */
@OWLClass(iri = Vocabulary.s_c_intent)
public class Intent
    extends Thing
{

    @OWLAnnotationProperty(iri = RDFS.LABEL)
    protected String name;
    @OWLAnnotationProperty(iri = DC.Elements.DESCRIPTION)
    protected String description;
    @Types
    protected Set<String> types;
    @Id(generated = true)
    protected String id;
    @Properties
    protected Map<String, Set<Object>> properties;
    @OWLObjectProperty(iri = Vocabulary.s_p_inv_dot_has_intent)
    @ParticipationConstraints({
        @ParticipationConstraint(owlObjectIRI = Vocabulary.s_c_dataset_exploring_journalist, max = 1)
    })
    protected DatasetExploringJournalist inv_dot_has_intent;
    @OWLObjectProperty(iri = Vocabulary.s_p_inv_dot_uses)
    @ParticipationConstraints({
        @ParticipationConstraint(owlObjectIRI = Vocabulary.s_c_dataset_exploration, max = 1)
    })
    protected DatasetExploration inv_dot_uses;

    public void setName(String name) {
        this.name = name;
    }

    public String getName() {
        return name;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public String getDescription() {
        return description;
    }

    public void setTypes(Set<String> types) {
        this.types = types;
    }

    public Set<String> getTypes() {
        return types;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getId() {
        return id;
    }

    public void setProperties(Map<String, Set<Object>> properties) {
        this.properties = properties;
    }

    public Map<String, Set<Object>> getProperties() {
        return properties;
    }

    public void setInv_dot_has_intent(DatasetExploringJournalist inv_dot_has_intent) {
        this.inv_dot_has_intent = inv_dot_has_intent;
    }

    public DatasetExploringJournalist getInv_dot_has_intent() {
        return inv_dot_has_intent;
    }

    public void setInv_dot_uses(DatasetExploration inv_dot_uses) {
        this.inv_dot_uses = inv_dot_uses;
    }

    public DatasetExploration getInv_dot_uses() {
        return inv_dot_uses;
    }

}
