
package cz.cvut.spipes.model;

import java.util.Date;
import java.util.Map;
import java.util.Set;

import cz.cvut.kbss.jopa.model.annotations.FetchType;
import cz.cvut.kbss.jopa.model.annotations.Id;
import cz.cvut.kbss.jopa.model.annotations.NamedNativeQueries;
import cz.cvut.kbss.jopa.model.annotations.NamedNativeQuery;
import cz.cvut.kbss.jopa.model.annotations.OWLAnnotationProperty;
import cz.cvut.kbss.jopa.model.annotations.OWLClass;
import cz.cvut.kbss.jopa.model.annotations.OWLDataProperty;
import cz.cvut.kbss.jopa.model.annotations.OWLObjectProperty;
import cz.cvut.kbss.jopa.model.annotations.ParticipationConstraint;
import cz.cvut.kbss.jopa.model.annotations.ParticipationConstraints;
import cz.cvut.kbss.jopa.model.annotations.Properties;
import cz.cvut.kbss.jopa.model.annotations.Types;
import cz.cvut.kbss.jopa.vocabulary.DC;
import cz.cvut.kbss.jopa.vocabulary.RDFS;
import cz.cvut.spipes.Vocabulary;


/**
 * This class was generated by the OWL2Java tool version $VERSION$
 */
@NamedNativeQueries({
        @NamedNativeQuery(name = "Transformation.findAll", query = "SELECT ?x WHERE { ?x a <" + Vocabulary.s_c_transformation + "> .}"),
        @NamedNativeQuery(name = "Transformation.findById", query = "SELECT ?x WHERE { ?x a <" + Vocabulary.s_c_transformation + "> .}")
})
@OWLClass(iri = Vocabulary.s_c_transformation)
public class Transformation
        extends Thing {

    @OWLAnnotationProperty(iri = RDFS.LABEL)
    protected String name;
    @OWLAnnotationProperty(iri = DC.Elements.DESCRIPTION)
    protected String description;
    @Types
    protected Set<String> types;
    @Id(generated = true)
    protected String id;
    @Properties
    protected Map<String, Set<Object>> properties;
    @OWLObjectProperty(iri = Vocabulary.s_p_has_input)
    @ParticipationConstraints({
            @ParticipationConstraint(owlObjectIRI = Vocabulary.s_c_source_dataset_snapshot, max = 1)
    })
    protected SourceDatasetSnapshot has_input;
    @OWLObjectProperty(iri = Vocabulary.s_p_has_output)
    @ParticipationConstraints({
            @ParticipationConstraint(owlObjectIRI = Vocabulary.s_c_target_dataset_snapshot, max = 1)
    })
    protected Set<Thing> has_output;
    @OWLObjectProperty(iri = Vocabulary.s_p_inv_dot_is_created_by)
    @ParticipationConstraints({
            @ParticipationConstraint(owlObjectIRI = Vocabulary.s_c_execution_context_dataset_source, max = 1)
    })
    protected ExecutionContextDatasetSource inv_dot_is_created_by;

    @OWLDataProperty(iri = Vocabulary.s_p_has_module_execution_start_date, fetch = FetchType.EAGER)
    protected Date start_date;

    @OWLDataProperty(iri = Vocabulary.s_p_has_module_execution_finish_date, fetch = FetchType.EAGER)
    protected Date finish_date;

    @OWLDataProperty(iri = Vocabulary.s_p_has_pipeline_execution_start_date, fetch = FetchType.EAGER)
    protected Date has_pipepline_execution_date;

    @OWLObjectProperty(iri = Vocabulary.s_p_has_module_id, fetch = FetchType.EAGER)
    protected String has_module_id;

    @OWLObjectProperty(iri = "http://onto.fel.cvut.cz/ontologies/dataset-descriptor/has-next", fetch = FetchType.EAGER)
    protected String has_next;

    @OWLDataProperty(iri = "http://onto.fel.cvut.cz/ontologies/s-pipes/has-output-model-triple-count", fetch = FetchType.EAGER)
    private Long output_triple_count;

    public void setName(String name) {
        this.name = name;
    }

    public String getName() {
        return name;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public String getDescription() {
        return description;
    }

    public void setTypes(Set<String> types) {
        this.types = types;
    }

    public Set<String> getTypes() {
        return types;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getId() {
        return id;
    }

    public void setProperties(Map<String, Set<Object>> properties) {
        this.properties = properties;
    }

    public Map<String, Set<Object>> getProperties() {
        return properties;
    }

    public void setHas_input(SourceDatasetSnapshot has_input) {
        this.has_input = has_input;
    }

    public SourceDatasetSnapshot getHas_input() {
        return has_input;
    }

    public void setHas_output(Set<Thing> has_output) {
        this.has_output = has_output;
    }

    public Set<Thing> getHas_output() {
        return has_output;
    }

    public void setInv_dot_is_created_by(ExecutionContextDatasetSource inv_dot_is_created_by) {
        this.inv_dot_is_created_by = inv_dot_is_created_by;
    }

    public ExecutionContextDatasetSource getInv_dot_is_created_by() {
        return inv_dot_is_created_by;
    }


    public Date getStart_date() {
        return start_date;
    }

    public void setStart_date(Date start_date) {
        this.start_date = start_date;
    }

    public Date getFinish_date() {
        return finish_date;
    }

    public void setFinish_date(Date finish_date) {
        this.finish_date = finish_date;
    }


    public Date getHas_pipepline_execution_date() {
        return has_pipepline_execution_date;
    }

    public void setHas_pipepline_execution_date(Date has_pipepline_execution_date) {
        this.has_pipepline_execution_date = has_pipepline_execution_date;
    }


    public String getHas_module_id() {
        return has_module_id;
    }

    public void setHas_module_id(String has_module_id) {
        this.has_module_id = has_module_id;
    }

    public String getHas_next() {
        return has_next;
    }

    public void setHas_next(String has_next) {
        this.has_next = has_next;
    }

    public long getOutput_triple_count() {
        return output_triple_count;
    }

    public void setOutput_triple_count(long output_triple_count) {
        this.output_triple_count = output_triple_count;
    }
}
