version: '3.7'

services:
  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - s-pipes-engine
      - s-pipes-engine-debug

  s-pipes-engine:
    image: ghcr.io/kbss-cvut/s-pipes/s-pipes-engine:latest
    ports:
      - "8081:8080"
    depends_on:
      - rdf4j
    environment:
      CONTEXT_PATH: "./../doc/examples;./../../s-pipes-modules"
      STORAGE_URL: "http://localhost:8080/db-server/rdf4j-server/repositories"
    volumes:
      - /tmp:/tmp
      - /home:/home
      - /usr/local/tomcat/temp/:/usr/local/tomcat/temp/
      - ./s-pipes-engine/s-pipes-progress-listener-config.ttl:/usr/local/tomcat/webapps/s-pipes/WEB-INF/classes/config.ttl
      - ./../doc/examples:/scripts/root:ro

  s-pipes-engine-debug:
    image: ghcr.io/kbss-cvut/s-pipes/s-pipes-engine-debug:latest
    ports:
      - "8082:8080"
    expose:
      - "8080"
    depends_on:
      - rdf4j
    environment:
      - STORAGE_URL=http://rdf4j:8080/rdf4j-server/repositories

  rdf4j:
    build:
      context: .
      dockerfile: ./db-server/Dockerfile_rdfj4
    ports:
      - "8080:8080"
    expose:
      - "8080"
    environment:
      - JAVA_OPTS=-Xms1g -Xmx4g
    volumes:
      - data:/var/rdf4j
      - logs:/usr/local/tomcat/logs

volumes:
  data:
  logs: