services:
  nginx:
    image: nginx:alpine
    ports:
      - "1234:80"
    volumes:
        - ./nginx/nginx.conf:/etc/nginx/templates/nginx.conf.template:ro
    depends_on:
      - s-pipes-engine
      - s-pipes-engine-debug
      - db-server
    environment:
        NGINX_ENVSUBST_OUTPUT_DIR: /etc/nginx
        APP_ORIGIN: "http://localhost:1234"

  s-pipes-engine:
    image: ghcr.io/kbss-cvut/s-pipes/s-pipes-engine:latest
    expose:
      - "8080"
    depends_on:
      - db-server
    environment:
      EXECUTION_CONFIGURL: "/usr/local/tomcat/webapps/s-pipes/WEB-INF/classes/config.ttl"
    volumes:
      - ./s-pipes-engine/s-pipes-progress-listener-config.ttl:/usr/local/tomcat/webapps/s-pipes/WEB-INF/classes/config.ttl
      - ./../doc/examples:/scripts/root:ro

  s-pipes-engine-debug:
    image: ghcr.io/kbss-cvut/s-pipes/s-pipes-engine-debug:latest
    expose:
      - "8080"
    depends_on:
      - db-server
    environment:
      - STORAGE_URL=http://db-server:7200/repositories
      - REPOSITORY_NAME=s-pipes-execution-log

  db-server:
      build:
          context: ./db-server
      environment:
          GDB_JAVA_OPTS: "-Dgraphdb.external-url=http://localhost:1234/db-server"
      expose:
          - "7200"
      volumes:
          - ./db-server/init-config:/repo-config:ro
          - db-server:/opt/graphdb/home

volumes:
  db-server: