PREFIX :<http://onto.fel.cvut.cz/ontologies/dataset-descriptor/s-p-o-summary/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX ld-cube: <http://purl.org/linked-data/cube#>
PREFIX ddo: <http://onto.fel.cvut.cz/ontologies/dataset-descriptor/>
PREFIX enh-spo-sum-desc: <http://onto.fel.cvut.cz/ontologies/dataset-descriptor/spo-summary-with-marginals/model/>

CONSTRUCT {
   ?configRoot :is-relevant-snapshot ?relevantDatasetSnapshot .
} WHERE  {
    {
            BIND(COALESCE(?executionId, STRUUID()) as ?localExecutionId)
    }
    {
        SELECT ?relevantDatasetSnapshot  ?snapshotGraphId2 ?datasetEndpointUrl2
        WHERE {
          SERVICE <http://onto.fel.cvut.cz/rdf4j-server/repositories/ddo-metadata-noinfer> {
              ?relevantDatasetSnapshot ddo:has-dataset ?relevantDataset .
              ?relevantDatasetSource ddo:offers-dataset ?relevantDataset .
              ?relevantDatasetSource ddo:has-endpoint-url ?datasetEndpointUrl2 .
              OPTIONAL {
                  ?relevantDatasetSource ddo:has-graph-id ?snapshotGraphId2 .
              }
          }
        }
    }

    FILTER(?datasetEndpointUrl = ?datasetEndpointUrl2)
    FILTER((!bound(?snapshotGraphId)) || (?snapshotGraphId = ?snapshotGraphId2))

    BIND(IRI(CONCAT(STR(:config), "-", ?localExecutionId)) as ?configRoot)
}