
package cz.cvut.sempipes.model;

import java.util.Map;
import java.util.Set;
import cz.cvut.kbss.jopa.CommonVocabulary;
import cz.cvut.kbss.jopa.model.annotations.Id;
import cz.cvut.kbss.jopa.model.annotations.OWLAnnotationProperty;
import cz.cvut.kbss.jopa.model.annotations.OWLClass;
import cz.cvut.kbss.jopa.model.annotations.OWLObjectProperty;
import cz.cvut.kbss.jopa.model.annotations.ParticipationConstraint;
import cz.cvut.kbss.jopa.model.annotations.ParticipationConstraints;
import cz.cvut.kbss.jopa.model.annotations.Properties;
import cz.cvut.kbss.jopa.model.annotations.Types;
import cz.cvut.sempipes.Vocabulary;


/**
 * This class was generated by the OWL2Java tool version $VERSION$
 * 
 */
@OWLClass(iri = Vocabulary.s_c_dataset_snapshot)
public class DatasetSnapshot
    extends Thing
{

    @OWLAnnotationProperty(iri = CommonVocabulary.RDFS_LABEL)
    protected String name;
    @OWLAnnotationProperty(iri = CommonVocabulary.DC_DESCRIPTION)
    protected String description;
    @Types
    protected Set<String> types;
    @Id(generated = true)
    protected String id;
    @Properties
    protected Map<String, Set<Object>> properties;
    @OWLObjectProperty(iri = Vocabulary.s_p_has_dataset)
    @ParticipationConstraints({
        @ParticipationConstraint(owlObjectIRI = Vocabulary.s_c_dataset, max = 1)
    })
    protected Set<Thing> has_dataset;
    @OWLObjectProperty(iri = Vocabulary.s_p_has_sub_dataset_snapshot)
    @ParticipationConstraints({
        @ParticipationConstraint(owlObjectIRI = Vocabulary.s_c_dataset_snapshot, max = -1)
    })
    protected Set<DatasetSnapshot> has_sub_dataset_snapshot;
    @OWLObjectProperty(iri = Vocabulary.s_p_inv_dot_has_published_dataset_snapshot)
    @ParticipationConstraints({
        @ParticipationConstraint(owlObjectIRI = Vocabulary.s_c_dataset_publication, max = 1)
    })
    protected Set<Thing> inv_dot_has_published_dataset_snapshot;
    @OWLObjectProperty(iri = Vocabulary.s_p_inv_dot_has_sub_dataset_snapshot)
    @ParticipationConstraints({
        @ParticipationConstraint(owlObjectIRI = Vocabulary.s_c_dataset_snapshot, max = 1)
    })
    protected DatasetSnapshot inv_dot_has_sub_dataset_snapshot;

    public void setName(String name) {
        this.name = name;
    }

    public String getName() {
        return name;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public String getDescription() {
        return description;
    }

    public void setTypes(Set<String> types) {
        this.types = types;
    }

    public Set<String> getTypes() {
        return types;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getId() {
        return id;
    }

    public void setProperties(Map<String, Set<Object>> properties) {
        this.properties = properties;
    }

    public Map<String, Set<Object>> getProperties() {
        return properties;
    }

    public void setHas_dataset(Set<Thing> has_dataset) {
        this.has_dataset = has_dataset;
    }

    public Set<Thing> getHas_dataset() {
        return has_dataset;
    }

    public void setHas_sub_dataset_snapshot(Set<DatasetSnapshot> has_sub_dataset_snapshot) {
        this.has_sub_dataset_snapshot = has_sub_dataset_snapshot;
    }

    public Set<DatasetSnapshot> getHas_sub_dataset_snapshot() {
        return has_sub_dataset_snapshot;
    }

    public void setInv_dot_has_published_dataset_snapshot(Set<Thing> inv_dot_has_published_dataset_snapshot) {
        this.inv_dot_has_published_dataset_snapshot = inv_dot_has_published_dataset_snapshot;
    }

    public Set<Thing> getInv_dot_has_published_dataset_snapshot() {
        return inv_dot_has_published_dataset_snapshot;
    }

    public void setInv_dot_has_sub_dataset_snapshot(DatasetSnapshot inv_dot_has_sub_dataset_snapshot) {
        this.inv_dot_has_sub_dataset_snapshot = inv_dot_has_sub_dataset_snapshot;
    }

    public DatasetSnapshot getInv_dot_has_sub_dataset_snapshot() {
        return inv_dot_has_sub_dataset_snapshot;
    }

}
