services:
  s-pipes-engine:
    image: ghcr.io/kbss-cvut/s-pipes/s-pipes-engine:latest
    ports:
      - "8081:8080"
    expose:
      - "8080"
    depends_on:
      - rdf4j
    volumes:
      - ../../../doc/examples:/scripts/root:ro

  s-pipes-engine-debug:
    image: ghcr.io/kbss-cvut/s-pipes/s-pipes-engine-debug:latest
    ports:
      - "8082:8080"
    expose:
      - "8080"
    depends_on:
      - rdf4j
    environment:
      - STORAGE_URL=http://rdf4j:8080/rdf4j-server/repositories

  rdf4j:
    build:
      context: .
      dockerfile: Dockerfile_rdfj4
    ports:
      - "8080:8080"
    expose:
      - "8080"
    environment:
      - JAVA_OPTS=-Xms1g -Xmx4g
    volumes:
      - data:/var/rdf4j
      - logs:/usr/local/tomcat/logs

volumes:
  data:
  logs:
