services:
  s-pipes-engine:
    ports:
      - "127.0.0.1:${JAVA_DEBUG_S_PIPES_ENGINE_PORT:-5005}:5005"
    environment:
      JAVA_OPTS: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=y,address=*:5005"
